ccflags-y += -I$(srctree)/drivers/misc/mediatek/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
obj-y	:=  bmm150.o