# Linux driver folder

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
obj-y	+=  NVTtouch_206.o
obj-y	+=  NVTtouch_206_ext_proc.o
obj-y	+=  NVTtouch_206_fw_update.o
obj-y	+=  NVTtouch_206_mp_ctrlram.o
